### ISSUE TITLE
Add the Transaction Key (locker) to the context of Script

### ISSUE THREAD

**Issue by kovax** [cristal-ise/kernel#149]
RoutingScript is executed during workflow enactment. Such a Script might need to access data created during the actual transaction in which it was triggered, so it can use the locker object as a trnasaction key to call `storage.get(CusterPath, locker)`.

**Comment by kovax** [comment]
This is also true for any script that can be executed on the server side:
- RoutingScript
- Script executed during collection management
- Script executed in implementations of JooqDomainHandler interface

**Comment by taurus227** [comment]
An error is thrown if a Script is executed without the `locker` (transaction key) parameter being specified by the caller. Solution: add default value for `locker`.
