### ISSUE TITLE
Domain path is not updated when the item "Name" property is modified

### ISSUE THREAD

**Issue by patrickclerc** [cristal-ise/kernel#158]
The domain path displayed in java GUI application is not updated when the item name is modified (even after a refresh). The domain path contains the item name as a leaf so it must follow the item name modifications.

**Comment by kovax** [comment]
This is by design. CreateItemFromDescription creates the 'inititial' DomainPath from the Name and the folder input paramter. But it is completely legal to change the Name independently from the DomainPath.
