### ISSUE TITLE
Evolve the CompositeActivity schema to accept multi-point edges

### ISSUE THREAD

**Issue by debbabi** [cristal-ise/kernel#162]
Actual Edges of the CompositeActivity are simple direct lines between two points. E.g.:

![screen shot 2017-11-23 at 10 14 34](https://user-images.githubusercontent.com/522491/33165859-9d033cd6-d038-11e7-9dd3-cbc4c5f6f3f1.png)

It could be more elegant and practical to have a multi-point Edges between activities. E.g.:

![screen shot 2017-11-23 at 09 45 35](https://user-images.githubusercontent.com/522491/33165826-81c0c466-d038-11e7-8285-4dcf9e346856.png)

Technically, we could add a vector of points (and their eventual metadata) to the `DirectedEdge` class, while we have to guarantee the compatibility with the previous schema. 

E.g., see the new <MultiPoints> tag:
`````
<NextDef ID="88" OriginVertexId="85" TerminusVertexId="84">
	<OriginPoint x="1900" y="400"/>
	<TerminusPoint x="1900" y="200”/>				
	<MultiPoints>
		<Point x=“..” y=“..” type=“..”/>
		<Point x=“..” y=“..” type=“..”/>
		<Point x=“..” y=“..” type=“..”/>
	</MultiPoints>
	<Properties>
		<KeyValuePair Key="Alias" String="true" isAbstract="false"/>
	</Properties>
</NextDef>
`````

Next version of the GUI (or third-party visualization tools) could benefit from this new structure to show and/or edit the multi-point edges of the graph, or even have more sophisticated layouts.

**Comment by kovax** [comment]
Let's discuss it when we design the new LifecycleEditor. Actually I would rather separate the representation data from the actual LifeCycle semantic by storing it in a separate xml/json.

**Comment by ogattaz** [comment]
In the future version 4, separating the representation data from the current Lyfecycle will be a big step forward.
The current demand is simply to be able to store optionnaly more informations in the wire definitions, to allow a third party editor to use them if needed.
The element "MultiPoints" has to be optionnal.
If the LifeCycle editor of the GUI client doesn't use it it's not an issue.

**Comment by kovax** [comment]
I do not see why this feature is needs to be in the kernel. Please explain why it cannot be done outside of the kernel.

**Comment by kovax** [comment]
I deleted my previous comment, because I totally misinterpreted the request. This can be done. although I do not see the usefulness without changing the gui project. But if you submit a PR I will review and integrate it.

**Comment by ogattaz** [comment]
According the discussion during the 22/01/2018 meetting, tis issue is splited in three :
1 - addition of intermediate points in the wire  ( this #162 issue) and validation with enhancements in the Gui client 
2 - jpg or png rendering using the kernel graph package
3 - svg rendering
