### ISSUE TITLE
Accept offset and size for all Lookup methods which return a list of Paths

### ISSUE THREAD

**Issue by debbabi** [cristal-ise/kernel#163]
Actually, `getChildred(Path)` method of the Lookup fetch all the list of children of the given path.

It would be more efficient to define an offset and a size for this method (or to define a new one with this extra parameters). The offset and size will be used in the SQL select statement when fetching data from the database.

**Comment by kovax** [comment]
This could be useful, although we need to keep in mind that the Lookup interface shall work on LDAP as  well. Also the getAgents(rolePath) and all of the search methods has to be changed as well.

**Comment by ogattaz** [comment]
Yes I agree with you : we have some work to do to stay generic and to be me more efficient...
Getting all the data and apply a filter ( paging or criterias) at the java side isn't the right way to be efficient.
So, enhancing the API of the LookUpManager to give more information to the implementations to be able to use the capabilities of the LDAP or SQL layer is the way we have to follow.

**Comment by kovax** [comment]
Olivier, this is not a company project where you can assign at your will... Even if you have rights, you shall keep the spirit of Open Source development and agree with the partner if he can do it or not.

**Comment by kovax** [comment]
Actually you can always fork the repo and implement the functionality and send a pull request. This is how Open Source development is done.

**Comment by ogattaz** [comment]
In my mind, the assignation of an issue isn't an order to do, it's just a way to obtain response (half duplex discussion ! ;-) )

**Comment by kovax** [comment]
Fair enough, although I usually answer to comments. More importantly the assignment means somebody committed to provide the solution, which is not the case yet.

**Comment by kovax** [comment]
Also. please do not assign milestones without discussing it with me. I do not think this issue can be done for 3.4 if we do not plan to implement the ldap version. That is a major change in functionality, not backward compatible, therefore it can only be done in 4.0.0. I want to follow 'semantic versioning' so it will not be confusing for other existing users.

**Comment by ogattaz** [comment]
According the discussion during the 22/01/2018 meeting:

Addition of new methods  :
- getChildren (startPath, offset, size)
- search (startPath, properties, offset, size)

**Comment by kovax** [comment]
- [ ] `PagedResult getChildren(Path path, int offset, int `limit);`
- [ ] `PagedResult search(Path start, PropertyArrayList props, int offset, int limit);`
- [ ] `PagedResult search(Path start, PropertyDescriptionList props, int offset, int limit);`
- [ ] `PagedResult searchAliases(ItemPath itemPath, int offset, int limit);`
- [ ] `PagedResult getAgents(RolePath rolePath, int offset, int limit)`
- [ ] `PagedResult getRoles(AgentPath agentPath, int offset, int limit)`
