### ISSUE TITLE
TransactionManager.getClusterContents does not look at uncommitted transactions

### ISSUE THREAD

**Issue by abranson** [cristal-ise/kernel#17]
History objects uses this method to generate the sequence of event ids. Currently, it will use the same ID if more than one Event is added per transaction, overwriting each one.

**Comment by kovax** [comment]
This was fixed in #149

https://github.com/cristal-ise/kernel/commit/d82053de2237a9bef35267034dc17ad0fa8737ae#diff-04311a32f3411402cc724ff1fac260d4
