### ISSUE TITLE
Store binary data

### ISSUE THREAD

**Issue by taurus227** [cristal-ise/kernel#202]
We would like to store profile pictures for our users. For this we need a facility to store binary data associated with items.

**Comment by kovax** [comment]
This shall be done as attachment to Outcomes. I will write here the implementation details. It will have an impact on corba iterface and its implemenmtation, proxy and lifecycle packages, and restapi, jooqdb and gui repos.

**Comment by kovax** [comment]
- [ ] Change idl method: add input parameter attachmen of type sequence<octet> to requestAction() and delegateAction()
- [ ] Pass this new parameter to each request() method of lifecycle classes so it can be stored when outcome is stored
- [ ] Change persistency classes to store the new binary data

**Comment by kovax** [comment]
Missing BuiltInVertexProperty AttachmentMimeTypes

**Comment by kovax** [comment]
Missing ItemProxy methods to handle OutcomeAttachment
