### ISSUE TITLE
Java 8 javascript engine Nashorn is incompatible with Rhino from Java 7

### ISSUE THREAD

**Issue by kovax** [cristal-ise/kernel#21]
Executing functional test cases compiled with Java 8 fails with this exception:

EXCEPTION:org.cristalise.kernel.scripting.ScriptingEngineException: Error executing script: ReferenceError: "importClass" is not defined in LocalObjectDefCreator at line number 2
	at org.cristalise.kernel.scripting.Script.execute(Script.java:518)
	at org.cristalise.kernel.entity.proxy.AgentProxy.callScript(AgentProxy.java:193)
	at org.cristalise.kernel.entity.proxy.AgentProxy.execute(AgentProxy.java:158)
	at org.cristalise.dev.test.scenario.BasicDevDescriptionIT.createNewEADesc(BasicDevDescriptionIT.groovy:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)

This is due to the incompatibility between the Rhino and Nashorn javascript engines:

http://www.oracle.com/technetwork/articles/java/jf14-nashorn-2126515.html
https://bugs.openjdk.java.net/browse/JDK-8025132

**Comment by kovax** [comment]
This is a Rhino-Hashorn migration guide:

https://wiki.openjdk.java.net/display/Nashorn/Rhino+Migration+Guide

**Comment by abranson** [comment]
Even with the compatibility script, there are differences between Nashorn and Rhino that will cause a difference in behaviour for existing scripts between java 7 and java 8. Considering that the JSR-223 implementation of Rhino was poor anyway, I would suggest that we drop JSR-223 entirely and revert to the BSF, which is now an [apache commons project](https://commons.apache.org/proper/commons-bsf/manual.html).

**Comment by ogattaz** [comment]
Andy,

Are you sure ?

What are the difference in behaviour you seen ?

A+

Olivier

**Comment by abranson** [comment]
Several problems are listed on here:

http://stackoverflow.com/questions/22502630/switching-from-rhino-to-nashorn

**Comment by ogattaz** [comment]
Andy,

I looked at the class « org.cristalise.kernel.lifecycle.instance.predefined.item.CreateItemFromDescription » and I asked me : How to set properties of the created item with values during its creation ?

Note :
In Cristal 2.3 there was no way to do it with the class  « fr.agilium.lifecycle.instance.predefined.CreateItemFromDescription », so a specialized class « CreateItemFromDescriptionWithProperties » was added.

        p.predInit("CreateItemFromDescription", "Create a new item using this item as its description", new CreateItemFromDescription());
        p.predInit("CreateItemFromDescriptionWithProperties", "Create a new item using this item as its description adding properties", new CreateItemFromDescriptionWithProperties());


In Cristalise kernel 3.0, I found that you can pass a list of properties in the third String of the « requestData » argument :
		PropertyArrayList initProps = input.length > 3?getInitProperties(input[3]):new PropertyArrayList();

The String representtaion of the « PropertyArrayList » must be a « marshalled PropertyArrayList »

Have you a piece of code showing how to use  that stuff ?

A complete snippet (test code) showing a Cristallise client creating a item from a description would be very precious !

Could-you publish your response in a public HOW-TO wiki ?

A+

Olivier

**Comment by kovax** [comment]
Olivier,

Let me try to explain, it is a very fundamental question, Andy shall
correct me if I say something silly :)

Check the LocalObjectDefCreator script in the dev module:

http://dev.cccs.uwe.ac.uk/redmine/projects/cristal-dev/repository/revisions/master/entry/src/main/resources/boot/SC/LocalObjectDefCreator.xml

You need to add 2 more parameters: third is the desc version, and forth
with the marshalled properties.

In principle you need to create a script similar to LocalObjectDefCreator,
a new Activity similiar to CreateNewLocalObjectDef and a new Schema
(OutcomeDesc) similar to NewDevObjectDef:

http://dev.cccs.uwe.ac.uk/redmine/projects/cristal-dev/repository/revisions/master/entry/src/main/resources/boot/EA/CreateNewLocalObjectDef.xml
http://dev.cccs.uwe.ac.uk/redmine/projects/cristal-dev/repository/revisions/master/entry/src/main/resources/boot/OD/NewDevObjectDef.xsd

The script will read the Outcome of the new activity and pack the data into
4 parameters compatible with CreateItemFromDescription.

I am actually adding new test cases, one of this calls the
ElementaryActivityDefFactory defined in the dev module:

https://github.com/cristal-ise/testing/blob/master/src/test/groovy/org/cristalise/dev/test/scenario/BasicDevDescriptionIT.groovy#L59

It is not simple, let me know if you need further explanation.

Zsolt

**Comment by abranson** [comment]
Proposal discussed with Olivier and Sandra today: migrate the internal scripts to Python and have no dependency on Javascript in the kernel at all. Then, if users choose to use Javascript, it's up to them to manage the Rhino/Nashorn problem themselves. It's an awfully hacky language favoured by cowboys and other ne'er-do-wells anyway.

**Comment by kovax** [comment]
So rather then changing couple of lines of code, all scripts will be
rewritten. Does it include dev module?

**Comment by abranson** [comment]
That is not an accurate presentation of the work required. It would be involve more than changing a couple of lines of code to support multiple javascript engines. It may even require holding different versions of scripts for each engine. Migration to Nashorn would involve rewriting scripts too.

The kernel currently contains one script (ServerNewEntity), and the dev module contains five. None of them are particularly long. Additionally, there is more python support in the scientific community than javascript, which is more of an agile driveway-tarmacing sort of language.

**Comment by kovax** [comment]
I was referring to the work of migrating JS Rhino to Nashorn only, which is
certainly less work than reimplementing all scripts in python. Also do I
get it right that python will be the only scripting supported by kernel?

**Comment by abranson** [comment]
Migrating the kernel from Rhino to Nashorn is very simple if you disregard the backwards compatibility issues. An easy way out would be to declare that the kernel no longer supports Java 7, and all scripts must be migrated to Nashorn, as even with the compatibility script Nashorn is not 100% compatible with Rhino.

The kernel supports any scripting engine that JSR-223 does, but the scripts included in the kernel must continue to support previous Java versions. There are two ways around this:

 1. Add support for holding different versions of scripts for different script engines for the same language. This is quite a large change to the kernel architecture, as we are already supporting temporal versioning and this would be orthogonal to that. 
 1. Use a language for the bundled kernel scripts that doesn't have these legacy compatibility problems. Jython is already a runtime dependency in the POM, so it's a natural choice.

Domain applications can use javascript if they want to, but they will have to manage the Rhino/Nashorn issue themselves, as they support their own scripts. They can either continue to use Java 7 for the time being, or migrate their scripts to Nashorn. This is better than us trying to impose Java versions on them from the kernel side.
