### ISSUE TITLE
Java exception getMessage() content is not transmitted form the server to the client

### ISSUE THREAD

**Issue by kovax** [cristal-ise/kernel#216]
This is the case for Script, the message from exception thrown by the Script is not available to the client

**Comment by taurus227** [comment]
Added a `details` field into the `InvalidCollectionModification` exception. Changed `AgentProxy` (used in restapi) to use the `details` field if it is present.
*Note:* Adding the field to all exceptions will make the error message disappear again, shadowed by the `details` field of another exception.
