### ISSUE TITLE
Documentation requests

### ISSUE THREAD

**Issue by abranson** [cristal-ise/kernel#22]
Add requests for improvements to the documentation on the wiki.

**Comment by smassonnat** [comment]
Regarding the predefinedSteps documentation, would it be possible to complete it, with the prerequisites ?

Eg. for the "CreateItemFromDescription" , the Item should have :
- a PropertyDescription Outcome 
- a workflow collection which contains a CAD

**Comment by abranson** [comment]
Done!

**Comment by abranson** [comment]
Module script sample, including new bootstrap event.

**Comment by debbabi** [comment]
Would you please add a documentation page for "Agents"?

**Comment by abranson** [comment]
Sure.

**Comment by abranson** [comment]
Data helpers
OutcomeInitiator
