### ISSUE TITLE
Simpler workflow routing

### ISSUE THREAD

**Issue by abranson** [cristal-ise/kernel#24]
Workflow split routing currently executes a user script, which is expected to produce a comma separated list of ids correspending to the names of branches that should be activated. This is the only situation wherein user-authored code is executed in the server process.
Replace this with a simple Viewpoint ref +xpath which retrieves data from an outcome instead. Existing scripts can be executed by a preceding activity as user code. Then the work is done by client processes, making the load balancing more efficient and the server.more reliable and secure.

**Comment by kovax** [comment]
This was implemented in ViewpointDataHelper
