### ISSUE TITLE
Integrate with apache shiro authentication and authorisation

### ISSUE THREAD

**Issue by kovax** [cristal-ise/kernel#248]
Redesign and implement authentication and authorisation support based on apache  

Related issues
#2: Authentication tokens for activity execution 
#5: Read permissions

**Comment by debbabi** [comment]
And so we will have an extensible Realm-based authentication/authorization? 
We could have a default realm provider that uses the actual Authenticator, but when we integrate Cristalise in an external IT we could implement other Realm providers so we cas use company's identity provider.

**Comment by kovax** [comment]
Yes, shiro's realms should be fully usable. Also Authenticator interface will be removed.
