### ISSUE TITLE
Client/Server connection encryption

### ISSUE THREAD

**Issue by abranson** [cristal-ise/kernel#3]
Add support for SSL/TLS encryption between client and server processes. This should be done for CORBA and the notification channel.

**Comment by LurkingFear** [comment]
#2 #5

**Comment by abranson** [comment]
Can I reference commits in other projects?

2f995692386aa0ab80cf3b366fda6934afea8a3b

**Comment by abranson** [comment]
Encryption on the CORBA channel will require a different ORB.

**Comment by kovax** [comment]
This will not be done while using corba.
