### ISSUE TITLE
Hook for activity timeout monitors

### ISSUE THREAD

**Issue by abranson** [cristal-ise/kernel#33]
Some domains need to change the state of activities automatically after a certain amount of time, for instance when a task expires.

**Comment by ogattaz** [comment]
« change the state of activities » => no it’s not our requirement

our requirement is :  after a certain amount of time ( corresponding to the reach of the Date limit ), someone (cf. a « timeout listener » ) has to be  alerted to do some thing described in the properties of the activity

My proposal:

You have to put in place a « Date limit monitor subsystem » in the server.
This subsystem is  based on the monitoring of a registry of started activities. 
Each time an activity having a Time max property is started, it is registered in the registry and its date limit is calculated

it would be simple if the « timeout listner » would be an agent having the role « internal_timeout_listner_role » : in this case, the « Date limit monitor subsystem » of the server could use the same mecanism as that is used to alert the other agents they have an activity matching one or more of their roles

On our side, this agent is a « special » agent (as the automatic runner agent is also a specific one) which is able to execute the « thing » described in the properties of the activity

**Comment by ogattaz** [comment]
From Andrew: "I believe this would be best implemented as a specific transition in the Agilium state machine, which has a different role than the ordinary activity role. This timeout job can then be pushed to a timeout manager, which can set timers according to any additional activity properties you like." 

=> No, a specific transition assumes that the activity state changed : it’s not our goal, the activity must stay in the same state, the action launched when the timeout appears must have no impact on the activity itself

An other proposal : a trigger mechanism 
if we can register a state listener called each time the state of the activities changed, we will be able to implement what I called the « Date limit monitor subsystem » 
so as we can give a ResourseLoader instance to  the kernel, It would be great to be able to give an IActivityStateListener instance

**Comment by abranson** [comment]
eb3437bdba1cf69ba0575e16d5379f7bf9577633 fixes special job pushing. Everything should be in place for this now.
