### ISSUE TITLE
Add a "Fatal error" listener

### ISSUE THREAD

**Issue by ogattaz** [cristal-ise/kernel#37]
Goal: To prevent fatal issues when the cristal library isn't alone in a JVM

Proposal : as we are today able to give the kernel a set of ClusterStorage instances using the cristalise properties map, we must be able to give a IFatalErrorListener instance to do what is correct after the ItemServer is stopped.

See the method : org.cristalise.kernel.process.AbstractMain.shutdown(int)

See below the trace of a wrong stop sequence : the OSGi framework running in the same JVM is broken when the "System.exit()" method is called by the kernel

FATAL  : Exception starting server components. Shutting down.
Transaction Manager: Closing storages
ProxyManager.shutdown() - flagging shutdown of server connections
SimpleTCPIPServer: Closing server for org.cristalise.kernel.entity.proxy.ProxyClientConnection on port 1553
SimpleTCPIPServer: Closing server for org.cristalise.kernel.scripting.ScriptConsole on port 52126
SimpleTCPIPServer: Server closed for org.cristalise.kernel.entity.proxy.ProxyClientConnection on port 1553
SimpleTCPIPServer - Servers still running: 1
SimpleTCPIPServer: Server closed for org.cristalise.kernel.scripting.ScriptConsole on port 52126
SimpleTCPIPServer - Servers still running: 0

**Comment by abranson** [comment]
Can you use the ShutdownHandler interface for this? You can register one with AbstractMain.setShutdownHandler(). It's used by the service wrapper already.

**Comment by ogattaz** [comment]
Using the shutdownHandler() is not enougth, the method "shutdown(int errCode)" kills the jvm just after
    
The problem is the call to System.exit()

		System.exit(errCode); // if we get here, we get out

**Comment by abranson** [comment]
The call to System.exit is there in case the shutdown handler fails to terminate the process, as that shutdown method cannot return, or else the call to Logger.die will return. What else could we do there?

**Comment by ogattaz** [comment]
The issue we have to solve is a modularization stuff :
The generic way to use the kernel is to embed it in a module using the way we can see in the Dev project.
So the question becomes : if our module contains other features than the kernel , how to prevent the brutal stopping ?
My proposal is just to put the "System.exit()" in the second else block as : 
``` java
    public static void shutdown(int errCode) {
    	if (shutdownHandler!= null)
    		shutdownHandler.shutdown(errCode, isServer);
    	else {
			try {
				Gateway.close();
			} catch (Exception ex) {
				Logger.error(ex);
			}
			System.exit(errCode); // if we get here, we get out
    	}
    }
```

**Comment by abranson** [comment]
Your proposal suffers from the same problem. If the shutdownHandler.shutdown() returns, then Logger.die will return!

**Comment by ogattaz** [comment]
if shutdownHandler.shutdown() throws  "RuntimeException"  it works well.

```java
	class CShutdownHandler implements ShutdownHandler {

		@Override
		public void shutdown(final int errCode, final boolean isServer) {

			pLogger.logSevere(this, "shutdown",
					"errCode=[%s] isServer=[%s] ==> CristalServerState=[%s]",
					errCode, isServer, EMachineState.STOPPED.name());

			if (errCode > 0) {
				pCristalServerState.setState(EMachineState.STOPPED);

				throw new RuntimeException(
						String.format("SHUTDOW errCode=[%s] isServer=[%s]",
								errCode, isServer));
			}
		}

	}
```

**Comment by abranson** [comment]
This would be still be caught higher up. I've been looking at thread killing, as this seems to be the only actual case where that would be a correct usage of that.
