### ISSUE TITLE
Writing and executing python script

### ISSUE THREAD

**Issue by smassonnat** [cristal-ise/kernel#39]
Cannot run python script on the kernel. I got the following error : cannot find the "python" script engine. Same error if i put "jython" in the script tag .

Solution :
To be able to write and run python script (on jython engine), I had to change the version of the jython dependency in the POM.xml to 2.5.3 (instead of the 2.5.0 which doesn't seem to contain the engine).
Work with both Java 7 and Java 8

**Comment by abranson** [comment]
Do you want me to do this, or would you like to push your POM into a pull request?

**Comment by smassonnat** [comment]
I think it will be quicker for you to modify it, than for me to do a pull request.
