### ISSUE TITLE
Activity description item collections

### ISSUE THREAD

**Issue by abranson** [cristal-ise/kernel#4]
Create the following links between description Items using collections:

* CompositeActivity to child Activity
* Activity to Schema
* Activity to Script
* Activity to StateMachine

Existing property based links to be preserved though deprecated, including slot overrides.

**Comment by abranson** [comment]
Every reference from instances must use UUIDs instead of names. This includes activity properties, events, and maybe even schema and viewpoint paths. It'll be up to the UIs to resolve these back into resource names.

**Comment by abranson** [comment]
Moving this to 3.2. Will be a big change that will cause instability, so it's best left for the next cycle.

**Comment by kovax** [comment]
This was done in 3.2, although in my vierw not complete. I will add issues to track the progress.
