### ISSUE TITLE
Module Item definitions cannot reference themselves in their collections.

### ISSUE THREAD

**Issue by smassonnat** [cristal-ise/kernel#41]
Cannot import from a module an item with a collection which have the same type a the Item. (recursive dependency).

Example 
![bug 41](https://cloud.githubusercontent.com/assets/9263650/9324197/5b18b9b4-4588-11e5-82b0-f128fc2515e5.JPG)

Give the following error 
![bug 41_2](https://cloud.githubusercontent.com/assets/9263650/9307783/caba3bd6-4500-11e5-924a-f3c0655cbd18.JPG)

**Comment by abranson** [comment]
It is difficult to know that it is a recursive link while it is still possible to roll back. It might be easier to support a special 'self' keyword here that tells the module managed to create a self-reference.

**Comment by kovax** [comment]
#168

**Comment by taurus227** [comment]
Depends on #182

**Comment by taurus227** [comment]
Fixed in #182
