### ISSUE TITLE
Remove the log sent to the stout

### ISSUE THREAD

**Issue by ogattaz** [cristal-ise/kernel#42]
The kernel produce a lot of log outside the logger.

See Below :

SimpleTCPIPServer: Created server for org.cristalise.kernel.scripting.ScriptConsole on port 15023
SimpleTCPIPServer: Created server for org.cristalise.kernel.entity.proxy.ProxyClientConnection on port 1553
Gateway.init() - ORB initialised. ORB is com.sun.corba.se.impl.orb.ORBImpl
Proxy Client: flagging shutdown.
Server 'localhost' initialised.
Bootstrap.run() setContextClassLoader=[org.cristalise.osgi.lib.kernel.core [60]]
SimpleTCPIPServer: Connection to Proxy Client Connection from /127.0.0.1
Connected to proxy server on localhost:1553
Bootstrap.run() - Verifying kernel boot data items
Bootstrap.verifyResource() - Item Default exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new StateMachine v0 to StateMachine Default
Bootstrap.verifyResource() - Item PredefinedStep exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new StateMachine v0 to StateMachine PredefinedStep
Bootstrap.verifyResource() - Item CompositeActivity exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new StateMachine v0 to StateMachine CompositeActivity
Bootstrap.verifyResource() - Item CompositeActivityDef exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new Schema v0 to Schema CompositeActivityDef
Bootstrap.verifyResource() - Item ElementaryActivityDef exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new Schema v0 to Schema ElementaryActivityDef
Bootstrap.verifyResource() - Item Module exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new Schema v0 to Schema Module
Bootstrap.verifyResource() - Item Agent exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new Schema v0 to Schema Agent
Bootstrap.verifyResource() - Item Role exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new Schema v0 to Schema Role
Bootstrap.verifyResource() - Item Item exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new Schema v0 to Schema Item
Bootstrap.verifyResource() - Item PredefinedStepOutcome exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new Schema v0 to Schema PredefinedStepOutcome
Bootstrap.verifyResource() - Item PropertyDescription exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new Schema v0 to Schema PropertyDescription
Bootstrap.verifyResource() - Item Schema exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new Schema v0 to Schema Schema
Bootstrap.verifyResource() - Item Script exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new Schema v0 to Schema Script
Bootstrap.verifyResource() - Item Errors exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new Schema v0 to Schema Errors
Bootstrap.verifyResource() - Item StateMachine exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new Schema v0 to Schema StateMachine
Bootstrap.verifyResource() - Item ItemInitialization exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new Schema v0 to Schema ItemInitialization
Bootstrap.verifyResource() - Item CreateNewItem exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new ElementaryActivityDef v0 to ElementaryActivityDef CreateNewItem
Bootstrap.verifyResource() - Item CreateNewAgent exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new ElementaryActivityDef v0 to ElementaryActivityDef CreateNewAgent
Bootstrap.verifyResource() - Item CreateNewRole exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new ElementaryActivityDef v0 to ElementaryActivityDef CreateNewRole
Bootstrap.verifyResource() - Item NoWorkflow exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new CompositeActivityDef v0 to CompositeActivityDef NoWorkflow
Bootstrap.verifyResource() - Item ServerItemWorkflow exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new CompositeActivityDef v0 to CompositeActivityDef ServerItemWorkflow
Bootstrap.verifyResource() - Item ServerNewEntity exists but version 0 not found! Attempting to insert new.
Bootstrap.verifyResource() - Writing new Script v0 to Script ServerNewEntity
Bootstrap.run() - Initialising Server Item Workflow
Registering module CristalLDAP
Module CristalLDAP registered
Registering module AgiliumngXmldb
Module AgiliumngXmldb registered
Registering module js-rhino
Module js-rhino registered
Registering module AgiliumngMain
Module AgiliumngMain registered
Bootstrap.run() - Bootstrapping complete

**Comment by abranson** [comment]
Hi,
The only message that should be going to stdout is the 'Server 'xxx' initialised' one. If you're getting more, then check when your log streams are added and removed - it'll default to System.out until then. Didn't you handle this yourself with the 'noNewLogStream' property you added?
