### ISSUE TITLE
ItemPath case insensitive

### ISSUE THREAD

**Issue by smassonnat** [cristal-ise/kernel#46]
It's not possible to edit the ItemPath of an Item by changing letters into Upper or Lower case.

Example:
The current ItemPath.
![bug_casesensitive_2](https://cloud.githubusercontent.com/assets/9263650/9329073/af6076c6-45ae-11e5-8a07-06918b3fc2cb.JPG)

If I try to rename it by changing the capital "A" of Agilium into a small "a", I got this error 

```
Item called at 2015-08-18 13:09:33.465: requestAction(/entity/2e1524f6-36ca-420e-997d-cc418ca3886f).
ItemImplementation::request(/entity/2e1524f6-36ca-420e-997d-cc418ca3886f) - Transition 0 on workflow/predefined/AddDomainPath by /entity/c76ef322-03a1-45bb-878f-204f8d2ab7b0
Propagating ObjectAlreadyExistsException back to the calling agent: IDL:org.cristalise.kernel/common/ObjectAlreadyExistsException:1.0  Entry already present.cn=Test10_workflow,cn=processWorkflow,cn=process,cn=agilium,cn=ActivityDesc,cn=desc,cn=domain,cn=dev,cn=cristal,dc=dev
```

The case sensitive/insensitive is also visble from the GUI Item tree :
All the item have an ItemPath with "agilium", except the Test10_workflow which has "Agilium".
![bug_casesensitive_1](https://cloud.githubusercontent.com/assets/9263650/9329122/33fd355e-45af-11e5-9915-04d8f4e070e1.JPG)

**Comment by abranson** [comment]
I think this comes from the fact that LDAP DNs are case-insensitive. Will look into this.

**Comment by kovax** [comment]
It is related to ldap, which is deprecated
