### ISSUE TITLE
Passwords are plaintext in config files and module definitions

### ISSUE THREAD

**Issue by ogattaz** [cristal-ise/kernel#47]
Allows the definition of the property "AdminPassword64"

Proposal :   in the "**Bootstrap:checkAdminAgents()** " method

```java
public static void checkAdminAgents() throws Exception {
    	
    	String adminPassword = null;
    	
    	// Retreives the value of the "AdminPassword64" property. Leaves "null" if it doesn't exist
    	//eg. AdminPassword64=bXlBZG1pblBhc3M= (myAdminPass)
    	String adminPassword64 = Gateway.getProperties().getString("AdminPassword64");
    	if (adminPassword64!=null && !adminPassword64.isEmpty() ){
    		
			// DatatypeConverter tool class available since java 1.5.
			// Throws IllegalArgumentException if value not conform
    		adminPassword = new String(
					DatatypeConverter.parseBase64Binary(adminPassword64));
    	}
    	// Retreives the value of the AdminPassword property. Returns "admin12345" if it doesn't exist
    	//eg.. AdminPassword=myAdminPass 
    	if (adminPassword==null){
    		adminPassword = Gateway.getProperties().getString("AdminPassword", "admin12345");
    	}

        // check for administrative user & admin role
    	...
```

**Comment by abranson** [comment]
What is this needed for?

**Comment by ogattaz** [comment]
the goal of this issue is to be able to give the needed passwords stored as "non human readable" value. 

my proposal is a sample, I wonder if the best way would be a new method "getB64String()" in "org.cristalise.kernel.utils.ObjectProperties" class

**Comment by abranson** [comment]
Base64 isn't a very good way to obfuscate data. I agree that we need to do something about these plaintext passwords. The config files aren't too bad because they can be stored in files on the server that are only readable by the server process (though perhaps the value could be removed from the server properties after it's finished with during bootstrap). What do you think?

**Comment by abranson** [comment]
Jet had an idea - we can just store the SHA hashed forms of the passwords in the config files, as we're doing that anyway. We're not using salting at the moment though. Maybe we need a property for defining password salt.

**Comment by ogattaz** [comment]
the salt must be calculated very early, so it could be good solution if it is given by the module hosting the kernel as a argument in the call of the "readC2KArgs()" method.
Note: the passed arguments are transformed in properties which are added to those read in the clc file
```java
        c2kProps.putAll(argProps); // args override connect file too
```
This way is available for the server and the client usage of the kernel

**Comment by abranson** [comment]
Explained the property loading sequence more clearly here: https://github.com/cristal-ise/kernel/wiki/CRISTALProperties

**Comment by abranson** [comment]
AdminPassword property, and password fields in modules, now can be set to pre-hashed passwords. They will not be hashed if they start with {algo}.

**Comment by ogattaz** [comment]
could-you explain how the module built on top of the kernel have to pass the hash salt ?

**Comment by abranson** [comment]
1. Set a password in LDAP using Apache Dir Studio or similar. This will generate different salt for each password.
2. Copy the 'userPassword' field from LDAP into the config file or module agent definition.

**Comment by ogattaz** [comment]
To implement SHA password, you modified the class « org.cristalise.lookup.ldap.LDAPLookupUtils » to add the import of  the class « org.castor.core.util.Base64Encoder; » 

This modification has a heavy impact on our side because it modifies the dependencies of our bundle  « ldap.persistency » in witch we reuse your classes of the package « org.cristalise.lookup.ldap » 

Agilium NG 
Using Castor (an XML tool ) in a class managing ldap stuff is not logic.

Why didn’t you choose the  class « com.novell.ldap.util.Base64 » present in the already used library « jldap 4.3 » ?

**Comment by abranson** [comment]
I didn't use the Novell one because it makes no difference on my side - that Base64 implementation was available in the dependencies of the project so I used it. 

It's not a problem to switch over to the other one.

**Comment by abranson** [comment]
Fixed
