### ISSUE TITLE
Accept base64 password in module definition file

### ISSUE THREAD

**Issue by ogattaz** [cristal-ise/kernel#48]
org.cristalise.kernel.entity.imports.ImportAgent.ImportAgent(String, String)

**Comment by abranson** [comment]
What is this needed for?

**Comment by ogattaz** [comment]
to be able to give store password as "non human readable value"

**Comment by ogattaz** [comment]
Could you add a description of the solution you implemented

**Comment by abranson** [comment]
I closed this as a duplicate of #47, as it will be solved the same way.
