### ISSUE TITLE
it's not possible to add a role to an existing agent

### ISSUE THREAD

**Issue by ogattaz** [cristal-ise/kernel#49]
eg. myModule.xml

```xml
		<Role jobList="false">myRole</Role>
		<Agent name="Admin" >
			<Role>myRole</Role>
		</Agent>
```

**Comment by abranson** [comment]
The comparisons between existing Items and Agents and their declaring modules isn't complete. This is one of the bits that isn't done. I think it would be better from a traceability point of view that these role assignments are done via predefined step.

**Comment by ogattaz** [comment]
In a module context (cf. modularization stuff), like the admin agent already exists during the loading of the domain specific module we have the need to complete the kernel definition of the Admin agent with some of our roles

This capability is localized in the method 
```java
org.cristalise.kernel.process.module.Module.importAll(ItemProxy, AgentProxy, String, boolean)
````
I wonder if in the case where the agent already exist the cycle would not be interrupted to be able to add the declared role list present in the xml agent element 
```Java 
		for (ImportAgent thisAgent : imports.getAgents()) {
			try {
				Gateway.getLookup().getAgentPath(thisAgent.name);
			    Logger.msg(3, "Module.importAll() - User '"+thisAgent.name+"' found.");
			    continue;
			 } catch (ObjectNotFoundException ex) { }
			 Logger.msg("Module.importAll() - User '"+thisAgent.name+"' not found. Creating.");
			thisAgent.create(systemAgent.getPath(), reset);
		}
```

**Comment by abranson** [comment]
I don't think it's a good idea to modify the 'admin' agent. You should have your own administrator account that you set up however you like. Items and Agents should not be defined in more that one module, nor should kernel Items be modified.
Aside from this, updating an Agent defined in a module with a changed Role set should be fixed.

**Comment by abranson** [comment]
Admin will be removed through #60
