### ISSUE TITLE
Predefined step "CreateAgentFromDescription" doesn't work

### ISSUE THREAD

**Issue by smassonnat** [cristal-ise/kernel#50]
The predefined step "CreateAgentFromDescription" doesn't work, because it's missing the password attribute to be able to create the entry in LDAP, see error log below.
```
CreateAgentFromDescription::request() - Starting.
ERROR  : Unknown Error: requestAction on /entity/f1bd9a63-9864-4c31-bb65-98818803f4a4 by org.cristalise.kernel.common.SystemKey@72906f executing workflow/predefined/CreateAgentFromDescription
EXCEPTION:org.cristalise.kernel.common.ObjectCannotBeUpdated: IDL:org.cristalise.kernel/common/ObjectCannotBeUpdated:1.0  Cannot create agent. No password given
	at org.cristalise.lookup.ldap.LDAPLookup.createAttributeSet(LDAPLookup.java:606)
	at org.cristalise.lookup.ldap.LDAPLookup.add(LDAPLookup.java:264)
	at org.cristalise.kernel.lifecycle.instance.predefined.agent.CreateAgentFromDescription.runActivityLogic(CreateAgentFromDescription.java:106)
```
There is no specific params to pass the password as an argument when calling the predefinedstep from a script and it's ignored if it is passed as a "Property" (see param4-PropertyArrayList in PredefinedStep documentation

**Comment by abranson** [comment]
Yes, this seems to be a problem from the LDAP lookup. I think it would be better if the password setting was always done in one place in future, so the password can be censored. SetAgentFromDescription should create the Agent with a null password, which can be set by an admin afterwards using the Agent predefined step, SetAgentPassword. I like this as a default behaviour, as some system Agents can be used by the server process without logging in, so should not have a password at all.
