### ISSUE TITLE
JavaDocs 3.0 & 3.1 not accessible

### ISSUE THREAD

**Issue by smassonnat** [cristal-ise/kernel#51]
The javadoc is not accessible from the wiki link :http://dev.cccs.uwe.ac.uk/docs/cristalise-kernel/3.1-SNAPSHOT/apidocs/index.html.

I'm getting the following error.

```
Forbidden

You don't have permission to access /docs/cristalise-kernel/3.1-SNAPSHOT/ on this server.
```

**Comment by abranson** [comment]
I've reset the permissions, and done a setgid on the parent directory so hopefully it'll stick. Let me know if it breaks again.

**Comment by abranson** [comment]
Seems to have held through the last build...
