### ISSUE TITLE
Create a role from a workflow.

### ISSUE THREAD

**Issue by smassonnat** [cristal-ise/kernel#53]
This is our context :
We would like to have in our module an Item "Role" and like we want to link this Item to the Cristal role, we would like to be able from our "RoleFactory" to create a new Role.

But, the problem is (if I'm not wrong), that the predefinedStep "CreateNewRole" is only accessible from the server and not from a workflow.

Is there any way to do that ?
If not, do you think it's possible to add a new predefined step for this purpose ?

**Comment by abranson** [comment]
The way to do this right now would be to locate the server item and call either the predefined step or the domain activity on that. That could change if we come up with a better Agent Description mechanism though.
