### ISSUE TITLE
Activity is set only inactive when next Activity is "run", i.e. its runNext() is called.

### ISSUE THREAD

**Issue by kovax** [cristal-ise/kernel#55]
Check CAExecutionTest 'Execute ElemAct using Done transition' test method.

It seems that State.isFinished and Transition.finishing flags of StateMachine are not used. This might not be a bug, but resolving this functionality could simplify AdvancementCalculator

**Comment by abranson** [comment]
To clarify, this relates to the way in which the active flag is transferred between activities. By design, the flag is not deactivated on a completed activity until another one has been activated. This means that the last activity of a workflows will stay active when the workflow is complete.

**Comment by abranson** [comment]
By design
