### ISSUE TITLE
Upgrade to latest Castor version 1.3.3?

### ISSUE THREAD

**Issue by debbabi** [cristal-ise/kernel#57]
The actual used version of Castor on the kernel is 1.3.2,
dId you tested the latest version of Castor 1.3.3?

**Comment by abranson** [comment]
I saw it some time ago, but it seemed to have a few spring dependencies that I wasn't sure about. Is there a compelling reason to upgrade?

**Comment by debbabi** [comment]
There is no compelling reason. 
I already have an OSGi bundle that encapsulates Castor lib v1.3.3 and I want to have the same as on the kernel. This is way I wounder if you plan to upgrade to this latest version. Otherwise, I can downgrade the Castor's version of my OSGi bundle to remain compatible with the kernel.

**Comment by abranson** [comment]
I tested it just now, while excluding the spring stuff, and it seemed to work ok, so give it a go if you like. It seems to be in active development again now though, Werner's created a repo for it on here and is working towards a 1.4:
https://github.com/castor-data-binding/castor
