### ISSUE TITLE
OrSplit/XOrSplit script evaluation exception is not propagated to the client

### ISSUE THREAD

**Issue by kovax** [cristal-ise/kernel#58]
OrSplit and XOrSplit  will throw an error when its RoutingScript is enbales a wrong number of branches. But that InvalidDataException in swallowed (see the link bellow) and the client doe not know why the workflow cannot proceed. 

https://github.com/cristal-ise/kernel/blob/master/src/main/java/org/cristalise/kernel/lifecycle/instance/CompositeActivity.java#L323

@smassonnat and @ogattaz could you please check if this is a required 'feature' in Agilium? 

You can also check the 3 test cases here covering this error handling:

https://github.com/cristal-ise/testing/blob/master/src/test/groovy/org/cristalise/kernel/test/lifecycle/instance/WfInitialiseSpecs.groovy#L193

WfInitialiseSpecs > OrSplit throws exception when no branch is enabled FAILED
WfInitialiseSpecs > XOrSplit throws exception when no branch is enabled FAILED
WfInitialiseSpecs > XOrSplit throws exception when more than one branch is enabled FAILED

**Comment by abranson** [comment]
Yes, that is a mistake. I should be swallowing only the AccessRightsException and propagating the rest back up as an InvalidData. I'll fix that.

Sometimes things are just bugs, you know ;)
