### ISSUE TITLE
Excpetion during boostrap of ModuleFactory

### ISSUE THREAD

**Issue by kovax** [cristal-ise/kernel#70]
Every time a dev cristal server is started with empty storage, the boostrap throws an InvalidTransitionException when recreating ModuleFactory

Check logs bellow:

Item::initialise(/entity/ac4a49d0-a156-48ec-ae1a-c54b616899f1) - agent:org.cristalise.kernel.common.SystemKey@19f47b7
History.addEvent() - creating new event for Done on Initialize in /entity/ac4a49d0-a156-48ec-ae1a-c54b616899f1
ClusterStorageManager.getClusterContents() - Finding contents of AuditTrail
org.cristalise.kernel.lifecycle.CompositeActivity::setFirstVertex() vertexID:0
DEBUG  : workflow runfirst
Loading activity state machine CompositeActivity v0
CompositeActivity v0 found in cache.
DEBUG  : workflowCompisiteActivity::run() state: 0
DEBUG  : Activity::run() path:workflow state:0
DEBUG  : workflow/domainCompisiteActivity::run() state: 0
DEBUG  : Activity::run() path:workflow/domain state:0
Loading activity state machine Default v0
Default v0 found in cache.
DEBUG  : Activity::run() path:workflow/domain/CreateNewModule state:0
Loading activity state machine Default v0
Default v0 found in cache.
Replacing Property SchemaType as 
History.addEvent() - creating new event for Done on domain in /entity/ac4a49d0-a156-48ec-ae1a-c54b616899f1
ClusterStorageManager.getClusterContents() - Finding contents of AuditTrail
Activity::auditEvent() - Event:0 was added to the AuditTrail
ClusterStorageManager.put() - writing Property/Type to LDAP Cluster Storage
LDAPClusterStorage.put() - /entity/ac4a49d0-a156-48ec-ae1a-c54b616899f1/Property/Type
LDAPLookupUtils.setProperty(Type) - creating new property.
LDAPLookupUtils.setProperty(Type) - setting to 'Factory'
ClusterStorageManager.put() - writing Property/Type to XMLDB
ClusterStorageManager.put() - Creating Strong cache for item /entity/ac4a49d0-a156-48ec-ae1a-c54b616899f1
ClusterStorageManager.put() - writing Property/Name to LDAP Cluster Storage
LDAPClusterStorage.put() - /entity/ac4a49d0-a156-48ec-ae1a-c54b616899f1/Property/Name
LDAPLookupUtils.setProperty(Name) - creating new property.
LDAPLookupUtils.setProperty(Name) - setting to 'ModuleFactory'
ClusterStorageManager.put() - writing Property/Name to XMLDB
ClusterStorageManager.put() - writing Outcome/ItemInitialization/0/0 to XMLDB
ClusterStorageManager.put() - writing ViewPoint/ItemInitialization/last to XMLDB
ClusterStorageManager.put() - writing Collection/workflow/last to XMLDB
ClusterStorageManager.put() - writing Collection/contents/last to XMLDB
ClusterStorageManager.put() - writing LifeCycle/workflow to XMLDB
CSM.clearCache() - removing /entity/ac4a49d0-a156-48ec-ae1a-c54b616899f1/AuditTrail
ClusterStorageManager.put() - writing AuditTrail/0 to XMLDB
DEBUG  : [] []
EXCEPTION:org.cristalise.kernel.common.InvalidTransitionException: IDL:org.cristalise.kernel/common/InvalidTransitionException:1.0  Attempted to finish a composite activity that had active children but was not Abortable
	at org.cristalise.kernel.lifecycle.instance.CompositeActivity.request(CompositeActivity.java:492)
	at org.cristalise.kernel.lifecycle.instance.CompositeActivity.runNext(CompositeActivity.java:343)
	at org.cristalise.kernel.lifecycle.instance.Activity.runNext(Activity.java:369)
	at org.cristalise.kernel.lifecycle.instance.CompositeActivity.runNext(CompositeActivity.java:350)
	at org.cristalise.kernel.lifecycle.instance.Activity.request(Activity.java:231)
	at org.cristalise.kernel.lifecycle.instance.CompositeActivity.request(CompositeActivity.java:494)
	at org.cristalise.kernel.lifecycle.instance.CompositeActivity.run(CompositeActivity.java:320)
	at org.cristalise.kernel.lifecycle.instance.CompositeActivity.request(CompositeActivity.java:485)
	at org.cristalise.kernel.lifecycle.instance.CompositeActivity.run(CompositeActivity.java:320)
	at org.cristalise.kernel.lifecycle.instance.Activity.runFirst(Activity.java:450)
	at org.cristalise.kernel.lifecycle.instance.Workflow.initialise(Workflow.java:226)
	at org.cristalise.kernel.entity.ItemImplementation.initialise(ItemImplementation.java:163)
	at org.cristalise.kernel.entity.TraceableEntity.initialise(TraceableEntity.java:109)
	at org.cristalise.kernel.entity.imports.ImportItem.create(ImportItem.java:163)
	at org.cristalise.kernel.process.module.Module.importAll(Module.java:149)
	at org.cristalise.kernel.process.module.ModuleManager.registerModules(ModuleManager.java:184)
	at org.cristalise.kernel.process.Bootstrap$1.run(Bootstrap.java:107)
	at java.lang.Thread.run(Thread.java:722)

**Comment by abranson** [comment]
Can't replicate that here. Have you got any more information?

**Comment by abranson** [comment]
Did you solve this?

**Comment by kovax** [comment]
I have just tired again. I have deleted all ldap and xmldb entries, realunched dev server (logLevel=8), and I get the same message

**Comment by abranson** [comment]
Do you have any local modifications to the kernel or dev that could be causing this?

**Comment by kovax** [comment]
Nothing at all.

**Comment by abranson** [comment]
We'll have to have a look at your setup when you come out then. To my knowledge you're the only person experiencing this.

**Comment by kovax** [comment]
I cannot figure out why it tries to complete the root CA. Here is the chain
of stacktraces:

EXCEPTION:org.cristalise.kernel.common.InvalidTransitionException:
IDL:org.cristalise.kernel/common/InvalidTransitionException:1.0  Attempted
to finish a composite activity that had active children but was not
Abortable
at
org.cristalise.kernel.lifecycle.instance.CompositeActivity.request(CompositeActivity.java:496)
at
org.cristalise.kernel.lifecycle.instance.CompositeActivity.runNext(CompositeActivity.java:344)
at
org.cristalise.kernel.lifecycle.instance.Activity.runNext(Activity.java:369)
at
org.cristalise.kernel.lifecycle.instance.CompositeActivity.runNext(CompositeActivity.java:354)
at
org.cristalise.kernel.lifecycle.instance.Activity.request(Activity.java:231)
at
org.cristalise.kernel.lifecycle.instance.CompositeActivity.request(CompositeActivity.java:498)
at
org.cristalise.kernel.lifecycle.instance.CompositeActivity.run(CompositeActivity.java:320)
at
org.cristalise.kernel.lifecycle.instance.CompositeActivity.request(CompositeActivity.java:489)
at
org.cristalise.kernel.lifecycle.instance.CompositeActivity.run(CompositeActivity.java:320)
at
org.cristalise.kernel.lifecycle.instance.Activity.runFirst(Activity.java:450)
at
org.cristalise.kernel.lifecycle.instance.Workflow.initialise(Workflow.java:226)
at
org.cristalise.kernel.entity.ItemImplementation.initialise(ItemImplementation.java:163)
at
org.cristalise.kernel.entity.TraceableEntity.initialise(TraceableEntity.java:109)
at
org.cristalise.kernel.entity.imports.ImportItem.create(ImportItem.java:163)
at org.cristalise.kernel.process.module.Module.importAll(Module.java:154)
at
org.cristalise.kernel.process.module.ModuleManager.registerModules(ModuleManager.java:186)
at org.cristalise.kernel.process.Bootstrap$1.run(Bootstrap.java:113)
at java.lang.Thread.run(Thread.java:722)

EXCEPTION:org.cristalise.kernel.common.InvalidDataException:
IDL:org.cristalise.kernel/common/InvalidDataException:1.0  Problem
completing composite activity:
IDL:org.cristalise.kernel/common/InvalidTransitionException:1.0  Attempted
to finish a composite activity that had active children but was not
Abortable
at
org.cristalise.kernel.lifecycle.instance.CompositeActivity.runNext(CompositeActivity.java:352)
at
org.cristalise.kernel.lifecycle.instance.Activity.runNext(Activity.java:369)
at
org.cristalise.kernel.lifecycle.instance.CompositeActivity.runNext(CompositeActivity.java:354)
at
org.cristalise.kernel.lifecycle.instance.Activity.request(Activity.java:231)
at
org.cristalise.kernel.lifecycle.instance.CompositeActivity.request(CompositeActivity.java:498)
at
org.cristalise.kernel.lifecycle.instance.CompositeActivity.run(CompositeActivity.java:320)
at
org.cristalise.kernel.lifecycle.instance.CompositeActivity.request(CompositeActivity.java:489)
at
org.cristalise.kernel.lifecycle.instance.CompositeActivity.run(CompositeActivity.java:320)
at
org.cristalise.kernel.lifecycle.instance.Activity.runFirst(Activity.java:450)
at
org.cristalise.kernel.lifecycle.instance.Workflow.initialise(Workflow.java:226)
at
org.cristalise.kernel.entity.ItemImplementation.initialise(ItemImplementation.java:163)
at
org.cristalise.kernel.entity.TraceableEntity.initialise(TraceableEntity.java:109)
at
org.cristalise.kernel.entity.imports.ImportItem.create(ImportItem.java:163)
at org.cristalise.kernel.process.module.Module.importAll(Module.java:154)
at
org.cristalise.kernel.process.module.ModuleManager.registerModules(ModuleManager.java:186)
at org.cristalise.kernel.process.Bootstrap$1.run(Bootstrap.java:113)
at java.lang.Thread.run(Thread.java:722)

EXCEPTION:org.cristalise.kernel.common.InvalidDataException:
IDL:org.cristalise.kernel/common/InvalidDataException:1.0  Problem
initializing composite activity:
IDL:org.cristalise.kernel/common/InvalidDataException:1.0  Problem
completing composite activity:
IDL:org.cristalise.kernel/common/InvalidTransitionException:1.0  Attempted
to finish a composite activity that had active children but was not
Abortable
at
org.cristalise.kernel.lifecycle.instance.CompositeActivity.run(CompositeActivity.java:328)
at
org.cristalise.kernel.lifecycle.instance.CompositeActivity.request(CompositeActivity.java:489)
at
org.cristalise.kernel.lifecycle.instance.CompositeActivity.run(CompositeActivity.java:320)
at
org.cristalise.kernel.lifecycle.instance.Activity.runFirst(Activity.java:450)
at
org.cristalise.kernel.lifecycle.instance.Workflow.initialise(Workflow.java:226)
at
org.cristalise.kernel.entity.ItemImplementation.initialise(ItemImplementation.java:163)
at
org.cristalise.kernel.entity.TraceableEntity.initialise(TraceableEntity.java:109)
at
org.cristalise.kernel.entity.imports.ImportItem.create(ImportItem.java:163)
at org.cristalise.kernel.process.module.Module.importAll(Module.java:154)
at
org.cristalise.kernel.process.module.ModuleManager.registerModules(ModuleManager.java:186)
at org.cristalise.kernel.process.Bootstrap$1.run(Bootstrap.java:113)
at java.lang.Thread.run(Thread.java:722)

ERROR  : Error initialising new item dev/ModuleFactory
EXCEPTION:org.cristalise.kernel.common.InvalidDataException:
IDL:org.cristalise.kernel/common/InvalidDataException:1.0  Problem
initializing composite activity:
IDL:org.cristalise.kernel/common/InvalidDataException:1.0  Problem
initializing composite activity:
IDL:org.cristalise.kernel/common/InvalidDataException:1.0  Problem
completing composite activity:
IDL:org.cristalise.kernel/common/InvalidTransitionException:1.0  Attempted
to finish a composite activity that had active children but was not
Abortable
at
org.cristalise.kernel.lifecycle.instance.CompositeActivity.run(CompositeActivity.java:328)
at
org.cristalise.kernel.lifecycle.instance.Activity.runFirst(Activity.java:450)
at
org.cristalise.kernel.lifecycle.instance.Workflow.initialise(Workflow.java:226)
at
org.cristalise.kernel.entity.ItemImplementation.initialise(ItemImplementation.java:163)
at
org.cristalise.kernel.entity.TraceableEntity.initialise(TraceableEntity.java:109)
at
org.cristalise.kernel.entity.imports.ImportItem.create(ImportItem.java:163)
at org.cristalise.kernel.process.module.Module.importAll(Module.java:154)
at
org.cristalise.kernel.process.module.ModuleManager.registerModules(ModuleManager.java:186)
at org.cristalise.kernel.process.Bootstrap$1.run(Bootstrap.java:113)
at java.lang.Thread.run(Thread.java:722)

EXCEPTION:org.cristalise.kernel.common.CannotManageException:
IDL:org.cristalise.kernel/common/CannotManageException:1.0  Problem
initialising new item. See server log.
at
org.cristalise.kernel.entity.imports.ImportItem.create(ImportItem.java:171)
at org.cristalise.kernel.process.module.Module.importAll(Module.java:154)
at
org.cristalise.kernel.process.module.ModuleManager.registerModules(ModuleManager.java:186)
at org.cristalise.kernel.process.Bootstrap$1.run(Bootstrap.java:113)
at java.lang.Thread.run(Thread.java:722)

EXCEPTION:org.cristalise.kernel.process.module.ModuleException: Error
importing items for module CristalDev
at
org.cristalise.kernel.process.module.ModuleManager.registerModules(ModuleManager.java:189)
at org.cristalise.kernel.process.Bootstrap$1.run(Bootstrap.java:113)
at java.lang.Thread.run(Thread.java:722)

**Comment by abranson** [comment]
This was caused by using a version of cristal-dev from before the open source launch. That version had a couple of workflows that incorrectly used the elementary activity state machine for composites. Since the CA abort functionality was added, this caused an error.
