### ISSUE TITLE
Extend the Agent.searchItem()

### ISSUE THREAD

**Issue by smassonnat** [cristal-ise/kernel#75]
Will it be possible to extend the current AgentProxy.searchItem() methode by adding another one with this signature:
``` java
searchItem(Path start, PropertyDescriptionList props);
```

This way we will be able to search not only on Item's name(cn) but also on their properties.

**Comment by abranson** [comment]
Yes, good idea. The AgentProxy is intended to provide access to most kernel functions without having to access the static stuff in the Gateway directly.
