### ISSUE TITLE
Add DomainPath to Agent

### ISSUE THREAD

**Issue by smassonnat** [cristal-ise/kernel#77]
How about adding a domainPath to the Agent item ?
It'll be really usefull to retrieve them, especially those that have no role assigned.

I was thinking, that maybe we could update the predefinedStep "CreateAgentFromDescription", so that it will take the domainPath into account if one is provided.

What do yo think ?

**Comment by kovax** [comment]
Can you give us an example for an Agent without any Role?

**Comment by abranson** [comment]
I agree that we should align CreateAgent and Item as much as possible, and leave password and role assignment to their specific predefined steps. As per OO, the constructor should leave the object in a usable state, but doesn't have to perform all initialization.
Perhaps all Agents should be given the root role on instantiation, and they can be given subroles later.

**Comment by kovax** [comment]
I agree, it should not be possible to create an Agent without a Role, like
an Item must have folder and Name. In this view Role is 'folder' of the
Agent.

**Comment by abranson** [comment]
If they gain DomainPaths then their presence in the Role tree is not so essential. However, it should be possible to target things at the root role and catch everybody.

**Comment by abranson** [comment]
099371c2ee6b3b6637a4d44408c670ccd3251ad0 should be right

**Comment by smassonnat** [comment]
Would be good to update the wiki with the new parameters of "CreateAgentFromDescription" ;)

**Comment by smassonnat** [comment]
I migth I've done something wrong, but if I try createing a agent without role, I get the followin error inside the kernel
```
Item called at 2015-10-14 11:36:55.084: requestAction(/entity/f331bef8-ec63-4683-adb3-35dd529b516a).
ItemImplementation::request(/entity/f331bef8-ec63-4683-adb3-35dd529b516a) - Transition 0 on workflow/predefined/CreateAgentFromDescription by /entity/f1bd9a63-9864-4c31-bb65-98818803f4a4
CreateAgentFromDescription::request() - Starting.
Propagating ObjectNotFoundException back to the calling agent: IDL:org.cristalise.kernel/common/ObjectNotFoundException:1.0  Role '' not found
```

It seems it's not able to find the default role...

**Comment by abranson** [comment]
I didn't get chance to test or document this before I went away, so thanks for the testing :)

**Comment by smassonnat** [comment]
With your last commit in lookup-ldap (26a1d71) , it's working fine.
