### ISSUE TITLE
Use Activity and CompositeActivite to define transaction demarcation

### ISSUE THREAD

**Issue by kovax** [cristal-ise/kernel#78]
It should be possible to declare the beginning and the end of a transaction based on the beginning and
end of an Elementary and Composite Activity execution. 

This would enable the following characteristics for the execution of Composite Activities and Workflows:
- ACID execution (e.g. Bootstrap)
- Fast execution of computational intensive Activities without the overhead of saving Events to the database

This funtionality requires #64 : Transactional cluster storage

**Comment by abranson** [comment]
The design of CRISTAL considers the activity state transition to be the atom of transaction. As each transition can come from different agents running in different client processes, I don't think it could handle long lived transactions such as you suggest any time soon. We could keep this in the future work list, but as it represents a major design direction change, I wouldn't like to put it on the roadmap without a clear example where it is necessary.
