### ISSUE TITLE
invalid information for LDAP lookup class in local.clc.example

### ISSUE THREAD

**Issue by jaduret** [cristal-ise/kernel#80]
Current local.clc.example is erroneous. Authenticator class reference path and Lookup class reference path are referencing kernel whilst they should not.

as such
Authenticator=org.cristalise.kernel.lookup.ldap.LDAPAuthManager
Lookup=org.cristalise.kernel.lookup.ldap.LDAPLookup

should be replaced by
Authenticator=org.cristalise.lookup.ldap.LDAPAuthManager
Lookup=org.cristalise.lookup.ldap.LDAPLookup

This avoids a ClassNotFoundException at startup.

**Comment by abranson** [comment]
Thanks, the example clc files in here and dev haven't been updated for a while. Those properties are actually no longer needed - they are supplied in the ldap-lookup module config so as long as that lib is on the classpath the correct classes will be used. You can still override them in the clc file if needed though - these values have a higher priority than the module properties..
