### ISSUE TITLE
Extends Script class to support user-provided ScriptEngineManagers

### ISSUE THREAD

**Issue by debbabi** [cristal-ise/kernel#83]
The User-provided ScriptEngineManager is given to the Gateway as a property.
If this property is not provided, the kernel uses the JVM default ScriptEngineManger (which uses Java Services to find engines).

**Comment by ogattaz** [comment]
Like for the other properties allowing us the capability to override the behaviour of the kernel, we can pass an instance of our implementation of the ScriptEngineManager.
