### ISSUE TITLE
Need documentation for the default StateMachine

### ISSUE THREAD

**Issue by debbabi** [cristal-ise/kernel#85]
We need to know the actual functionning of the default StateMachine, and how we can provide our own one.
https://github.com/cristal-ise/kernel/wiki/StateMachine

**Comment by abranson** [comment]
I'm sure I wrote a long page about that with diagrams, but it must have been on the old Redmine which is currently broken. Will have to try to resurrect it.

**Comment by kovax** [comment]
There is a test class for that:

https://github.com/cristal-ise/testing/blob/master/src/test/groovy/org/cristalise/kernel/test/lifecycle/instance/CustomStateMachineSpecs.groovy

**Comment by abranson** [comment]
Maybe there should be links from the docs to test classes when available?

**Comment by abranson** [comment]
I've got the old redmine working again on http://dev.cccs.uwe.ac.uk/, and I think I should copy over every un-migrated wiki page raw. It's more important to have everything moved than have it looking nice.

**Comment by abranson** [comment]
Done
