### ISSUE TITLE
Look at the compilation capability of the script engine to enhance performance

### ISSUE THREAD

**Issue by ogattaz** [cristal-ise/kernel#98]
Look at the compilation capability of the new Rhino engine to enhance performance.

**Comment by kovax** [comment]
This seem to be implemented already. Check this code:

https://github.com/cristal-ise/kernel/blob/master/src/main/java/org/cristalise/kernel/scripting/Script.java#L606

**Comment by kovax** [comment]
Script are compiled when they are instantiated form XML, Check method setScriptData()
